package Komunikator;

public enum ETypZdarzenia {
	DODAJ_PRACOWNIKA_MENU,
	EDYTUJ_PRACOWNIKA_MENU,
	USUN_PRACOWNIKA_MENU,
	WYBRANO_ID_PRACOWNIKA_EDYCJA,
	WYBRANO_ID_PRACOWNIKA_USUN,
	ZAKONCZONO_EDYCJE_PRACOWNIKA
}
